name: Deploy to Firebase

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Firebase Hosting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies (exprezzzo-global)
        working-directory: apps/exprezzzo-global
        run: npm ci

      - name: Build site (exprezzzo-global)
        working-directory: apps/exprezzzo-global
        run: npm run build

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_EXPREZZZO_SUITE }}"
          channelId: live
          projectId: exprezzzo-suite