name: Deploy to Firebase

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        working-directory: apps/exprezzzo-global
        run: npm ci

      - name: Build project
        working-directory: apps/exprezzzo-global
        run: npm run build

      - name: Deploy to Firebase Hosting
        run: |
          cd ../..  # ensure workspace-root, so firebase.json is found
          firebase deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}