name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main  # Adjust if your default branch is different

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Optional: Install dependencies and build your project
      # Uncomment and modify the following steps if needed
      # - name: Install dependencies
      #   run: npm install

      # - name: Build project
      #   run: npm run build

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          projectId: exprezzzo-sandbox-admin
          channelId: live
